services:
  web-1:
    build: .
    image: personal-website
    ports:
      - "8080:80"
    volumes:
      - ./site-1:/usr/share/nginx/html

  web-2:
    build: .
    image: personal-website
    ports:
      - "8081:80"
    volumes:
      - ./site-2:/usr/share/nginx/html
  web-3:
      build: .
      image: personal-website
      ports:
        - "8082:80"
      volumes:
        - ./site-3:/usr/share/nginx/html
  web-4:
      build: .
      image: personal-website
      ports:
        - "8083:80"
      volumes:
        - ./site-4:/usr/share/nginx/html

  web-5:
      build: .
      image: personal-website
      ports:
        - "8084:80"
      volumes:
        - ./site-5:/usr/share/nginx/html

  web-6:
      build: .
      image: personal-website
      ports:
        - "8085:80"
      volumes:
        - ./site-6:/usr/share/nginx/html

  web-7:
      build: .
      image: personal-website
      ports:
        - "8086:80"
      volumes:
        - ./site-7:/usr/share/nginx/html

  web-8:
      build: .
      image: personal-website
      ports:
        - "8087:80"
      volumes:
        - ./site-8:/usr/share/nginx/html

  web-9:
      build: .
      image: personal-website
      ports:
        - "8088:80"
      volumes:
        - ./site-9:/usr/share/nginx/html

  web-10:
      build: .
      image: personal-website
      ports:
        - "8089:80"
      volumes:
        - ./site-10:/usr/share/nginx/html
