# Bonus file to complete Extra Credit
# Run `docker compose down -v` to remove volumes

services:
  code-server-1:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server-1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - code_server_1_config:/config
    ports:
      - "8443:8443"
    restart: unless-stopped

  code-server-2:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server-2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - code_server_2_config:/config
    ports:
      - "8444:8443"
    restart: unless-stopped

  code-server-3:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server-3
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - code_server_3_config:/config
    ports:
      - "8445:8443"
    restart: unless-stopped

  code-server-4:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server-4
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - code_server_4_config:/config
    ports:
      - "8446:8443"
    restart: unless-stopped

  code-server-5:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server-5
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - code_server_5_config:/config
    ports:
      - "8447:8443"
    restart: unless-stopped

volumes:
  code_server_1_config:
  code_server_2_config:
  code_server_3_config:
  code_server_4_config:
  code_server_5_config:
